// AUTO-GERADO por build_cases.py. Nao editar manualmente.
window.PROFILE = {
  "name": "Enzo Marinho",
  "initials": "EM",
  "role": "Direção & Conteúdo",
  "location": "Araçatuba · SP",
  "tagline_a": "Conteúdo com direção,",
  "tagline_b": "ritmo e intenção.",
  "hero_title": "Direção, roteiro e edição para vídeos que parecem simples porque foram bem pensados.",
  "hero_sub": "Uma seleção curta de trabalhos com problema, decisão criativa e entrega. O foco é provar clareza, ritmo e acabamento antes da conversa comercial.",
  "about": "Eu uno estratégia, roteiro, direção, captação e edição para transformar assuntos difíceis em conteúdo claro, humano e assistível. O foco não é aparecer: é fazer o trabalho do cliente ficar mais fácil de entender.",
  "process": [
    "Estratégia",
    "Roteiro",
    "Direção",
    "Captação",
    "Edição",
    "Remotion"
  ],
  "methods": [
    {
      "title": "Diagnóstico",
      "text": "Antes de gravar, defino público, promessa e objeção principal."
    },
    {
      "title": "Roteiro visual",
      "text": "A ideia vira cenas, ganchos e uma ordem que segura atenção."
    },
    {
      "title": "Direção no set",
      "text": "Captação, ritmo, atuação e detalhes práticos resolvidos na gravação."
    },
    {
      "title": "Edição e entrega",
      "text": "Cortes, motion, cor, som e versões finais prontas para publicar."
    }
  ],
  "clients": [
    "VOTI Software",
    "8848 Jiu-Jitsu",
    "Kayky Pitondo",
    "Magnos Steel",
    "Catvi"
  ],
  "services": [
    {
      "number": "01",
      "title": "Conteúdo recorrente",
      "description": "Uma gravação vira um sistema de vídeos para o mês.",
      "detail": "Estratégia · vídeo longo · cortes verticais · distribuição"
    },
    {
      "number": "02",
      "title": "Projeto dirigido",
      "description": "Campanha, anúncio ou vídeo especial com direção de ponta a ponta.",
      "detail": "Conceito · roteiro · captação · edição · entrega final"
    }
  ],
  "contact": {
    "whatsapp": "https://wa.me/5518981196746?text=Oi%20Enzo,%20vi%20seu%20portf%C3%B3lio%20e%20quero%20conversar.",
    "instagram": "https://instagram.com/enzosmarinho",
    "linkedin": "https://www.linkedin.com/in/enzo-marinho-727200320",
    "youtube": "https://youtube.com/@votigestao",
    "email": "enzo.marinho@hotmail.com"
  }
};
window.CASES = [
  {
    "id": "DQfTWkhiK4k",
    "title": "Funcionário perfeito",
    "client": "VOTI Software",
    "category": "direcao",
    "categoryLabel": "Direção",
    "format": "Reel",
    "role": "Roteiro · direção · edição",
    "problem": "Mostrar o valor do software sem soar como propaganda técnica.",
    "direction": "Conceito do funcionário perfeito para humanizar a ferramenta em tom leve.",
    "deliverable": "Reel roteirizado e dirigido, pronto para o feed.",
    "year": "2025",
    "layout": "wide",
    "orientation": "portrait",
    "featured": true,
    "permalink": "https://www.instagram.com/reel/DQfTWkhiK4k/",
    "thumb": "assets/thumbs/ig_DQfTWkhiK4k.jpg",
    "poster": "assets/posters/DQfTWkhiK4k.jpg",
    "preview": "assets/previews/DQfTWkhiK4k.mp4",
    "cardImage": "assets/posters/DQfTWkhiK4k.jpg"
  },
  {
    "id": "DUf-ODMDWqA",
    "title": "No tatame",
    "client": "8848 Jiu-Jitsu",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Captação · edição · ritmo",
    "problem": "Traduzir a energia do treino para atrair novos alunos.",
    "direction": "Captação dentro do tatame e corte no ritmo do movimento.",
    "deliverable": "Reel vertical de impacto para a academia.",
    "year": "2026",
    "layout": "tall",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DUf-ODMDWqA/",
    "thumb": "assets/thumbs/ig_DUf-ODMDWqA.jpg",
    "poster": "assets/posters/DUf-ODMDWqA.jpg",
    "preview": "assets/previews/DUf-ODMDWqA.mp4",
    "cardImage": "assets/thumbs/ig_DUf-ODMDWqA.jpg"
  },
  {
    "id": "qBTk1irwDc4",
    "title": "Tour pela Catvi",
    "client": "VOTI · Catvi",
    "category": "direcao",
    "categoryLabel": "Direção",
    "format": "Short",
    "role": "Captação em loja · motion 3D",
    "problem": "Apresentar a loja Catvi de forma dinâmica e memorável.",
    "direction": "Tour gravado no ponto físico com apoio de motion 3D.",
    "deliverable": "Short de apresentação para o canal.",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://youtu.be/qBTk1irwDc4",
    "thumb": "assets/thumbs/qBTk1irwDc4.jpg",
    "poster": "assets/posters/qBTk1irwDc4.jpg",
    "preview": "assets/previews/qBTk1irwDc4.mp4",
    "cardImage": "assets/posters/qBTk1irwDc4.jpg"
  },
  {
    "id": "ADKpionmFiw",
    "title": "Treino de superiores",
    "client": "Kayky Pitondo",
    "category": "long-form",
    "categoryLabel": "Long-form",
    "format": "40 min",
    "role": "Estrutura · edição · color",
    "problem": "Manter a atenção em um treino longo do início ao fim.",
    "direction": "Estrutura por blocos e correção de cor para padronizar a imagem.",
    "deliverable": "Vídeo long-form de 40 min editado e finalizado.",
    "year": "2026",
    "layout": "wide",
    "orientation": "landscape",
    "permalink": "https://youtu.be/ADKpionmFiw",
    "thumb": "assets/thumbs/ADKpionmFiw.jpg",
    "poster": "assets/posters/ADKpionmFiw.jpg",
    "preview": "assets/previews/ADKpionmFiw.mp4",
    "cardImage": "assets/thumbs/ADKpionmFiw.jpg"
  },
  {
    "id": "DXiIx4_kQ-0",
    "title": "Seu DRE mentiu",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Hook · demonstração · edição",
    "problem": "Explicar uma dor financeira do negócio de forma simples.",
    "direction": "Abertura com hook direto e demonstração do problema na tela.",
    "deliverable": "Reel educativo com hook e demonstração.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DXiIx4_kQ-0/",
    "thumb": "assets/thumbs/ig_DXiIx4_kQ-0.jpg",
    "poster": "assets/posters/DXiIx4_kQ-0.jpg",
    "preview": "assets/previews/DXiIx4_kQ-0.mp4",
    "cardImage": "assets/thumbs/ig_DXiIx4_kQ-0.jpg"
  },
  {
    "id": "DYC7byPyEnW",
    "title": "Oferta Magnos",
    "client": "Magnos Steel",
    "category": "anuncios",
    "categoryLabel": "Anúncios",
    "format": "Anúncio",
    "role": "Apresentação · cortes · CTA",
    "problem": "Comunicar uma oferta e levar o público à ação.",
    "direction": "Apresentação objetiva, cortes ágeis e CTA claro no fechamento.",
    "deliverable": "Anúncio pronto para veiculação.",
    "year": "2026",
    "layout": "wide",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DYC7byPyEnW/",
    "thumb": "assets/thumbs/ig_DYC7byPyEnW.jpg",
    "poster": "assets/posters/DYC7byPyEnW.jpg",
    "preview": "assets/previews/DYC7byPyEnW.mp4",
    "cardImage": "assets/thumbs/ig_DYC7byPyEnW.jpg"
  },
  {
    "id": "DSldztZCA9P",
    "title": "Carta ao Papai Noel",
    "client": "VOTI Software",
    "category": "direcao",
    "categoryLabel": "Direção",
    "format": "Reel",
    "role": "Narrativa · atuação · branding",
    "problem": "Criar uma peça sazonal sem perder a assinatura da marca.",
    "direction": "Narrativa simples, atuação guiada e fechamento com presença de marca.",
    "deliverable": "Reel narrativo para campanha de fim de ano.",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DSldztZCA9P/",
    "thumb": "assets/thumbs/ig_DSldztZCA9P.jpg",
    "poster": "assets/posters/DSldztZCA9P.jpg",
    "preview": "assets/previews/DSldztZCA9P.mp4",
    "cardImage": "assets/thumbs/ig_DSldztZCA9P.jpg"
  },
  {
    "id": "DWpa8TQCKvX",
    "title": "Qual produto dá mais lucro?",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Copy · produto · retenção",
    "problem": "Transformar uma pergunta de gestão em conteúdo fácil de acompanhar.",
    "direction": "Copy direta e edição orientada por retenção para sustentar a explicação.",
    "deliverable": "Reel de produto com argumento claro e cortes objetivos.",
    "year": "2026",
    "layout": "wide",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DWpa8TQCKvX/",
    "thumb": "assets/thumbs/ig_DWpa8TQCKvX.jpg",
    "poster": "assets/posters/DWpa8TQCKvX.jpg",
    "preview": "assets/previews/DWpa8TQCKvX.mp4",
    "cardImage": "assets/thumbs/ig_DWpa8TQCKvX.jpg"
  },
  {
    "id": "DKkdTYyItAy",
    "title": "Bastidores na Catvi",
    "client": "VOTI · Catvi",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Vlog · prova de campo · edição",
    "problem": "Mostrar a operação real por trás do produto sem parecer peça encenada.",
    "direction": "Bastidores em campo com cortes de vlog e prova visual do processo.",
    "deliverable": "Reel de bastidores para reforço de confiança.",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DKkdTYyItAy/",
    "thumb": "assets/thumbs/ig_DKkdTYyItAy.jpg",
    "poster": "assets/posters/DKkdTYyItAy.jpg",
    "preview": "assets/previews/DKkdTYyItAy.mp4",
    "cardImage": "assets/thumbs/ig_DKkdTYyItAy.jpg"
  }
];
window.EXTRA_CLIPS = [
  {
    "id": "DUJfuJsCPir",
    "title": "WhatsApp conectado",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Demonstração · produto · clareza",
    "problem": "Mostrar uma integração técnica sem transformar o vídeo em tutorial frio.",
    "direction": "Roteiro guiado por ação na tela, com ritmo de demonstração curta.",
    "deliverable": "Reel de produto para explicar uma função específica.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DUJfuJsCPir/",
    "thumb": "assets/thumbs/ig_DUJfuJsCPir.jpg",
    "poster": "assets/posters/DUJfuJsCPir.jpg",
    "preview": "assets/previews/DUJfuJsCPir.mp4",
    "cardImage": "assets/thumbs/ig_DUJfuJsCPir.jpg"
  },
  {
    "id": "DV9deuiCHea",
    "title": "Loja física + online",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Copy · dor real · produto",
    "problem": "Transformar retrabalho de estoque e preço em uma dor fácil de reconhecer.",
    "direction": "Começo por pergunta direta e conexão com situação real de varejo.",
    "deliverable": "Reel educativo para topo de funil.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DV9deuiCHea/",
    "thumb": "assets/thumbs/ig_DV9deuiCHea.jpg",
    "poster": "assets/posters/DV9deuiCHea.jpg",
    "preview": "assets/previews/DV9deuiCHea.mp4",
    "cardImage": "assets/thumbs/ig_DV9deuiCHea.jpg"
  },
  {
    "id": "DTgXN2FiDV6",
    "title": "Sintoma de gestão",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Hook · analogia · edição",
    "problem": "Chamar atenção para uma dor de gestão usando uma entrada mais memorável.",
    "direction": "Abordagem por sintoma e cura para tornar o tema técnico mais assistível.",
    "deliverable": "Reel de awareness para social.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DTgXN2FiDV6/",
    "thumb": "assets/thumbs/ig_DTgXN2FiDV6.jpg",
    "poster": "assets/posters/DTgXN2FiDV6.jpg",
    "preview": "assets/previews/DTgXN2FiDV6.mp4",
    "cardImage": "assets/thumbs/ig_DTgXN2FiDV6.jpg"
  },
  {
    "id": "blYFchVi4xg",
    "title": "Sistema de Natal",
    "client": "VOTI Software",
    "category": "anuncios",
    "categoryLabel": "Anúncios",
    "format": "Short",
    "role": "Sazonal · roteiro · edição",
    "problem": "Aproveitar uma data comercial sem perder o vínculo com produto.",
    "direction": "Gancho sazonal com linguagem leve e foco em preparação de venda.",
    "deliverable": "Short sazonal para campanha de fim de ano.",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://youtu.be/blYFchVi4xg",
    "thumb": "assets/thumbs/blYFchVi4xg.jpg",
    "poster": "assets/posters/blYFchVi4xg.jpg",
    "preview": "assets/previews/blYFchVi4xg.mp4",
    "cardImage": "assets/posters/blYFchVi4xg.jpg"
  },
  {
    "id": "DGLMxcXRRJ4",
    "title": "Caso na Padaria Bom Menino",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Vlog · caso real · prova",
    "problem": "Gerar confiança no sistema com um cliente real, não com promessa.",
    "direction": "Estudo de caso gravado no ponto do cliente, com autoridade e números.",
    "deliverable": "Reel de prova social em campo.",
    "year": "2025",
    "layout": "standard",
    "orientation": "landscape",
    "permalink": "https://www.instagram.com/reel/DGLMxcXRRJ4/",
    "thumb": "assets/thumbs/ig_DGLMxcXRRJ4.jpg",
    "poster": "assets/posters/DGLMxcXRRJ4.jpg",
    "preview": "assets/previews/DGLMxcXRRJ4.mp4",
    "cardImage": "assets/posters/DGLMxcXRRJ4.jpg"
  },
  {
    "id": "DOzGHz2iLGz",
    "title": "E se você fosse de uma oficina?",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Verticalização · energia · edição",
    "problem": "Mostrar que o sistema atende a um nicho específico, não só o genérico.",
    "direction": "Infotenimento B2B de alta energia focado no segmento.",
    "deliverable": "Reel de verticalização para oficinas.",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DOzGHz2iLGz/",
    "thumb": "assets/thumbs/ig_DOzGHz2iLGz.jpg",
    "poster": "assets/posters/DOzGHz2iLGz.jpg",
    "preview": "assets/previews/DOzGHz2iLGz.mp4",
    "cardImage": "assets/thumbs/ig_DOzGHz2iLGz.jpg"
  },
  {
    "id": "DHtF3CvxAlF",
    "title": "Estoque no automático",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Talking head · direct response",
    "problem": "Vender produtividade para quem ainda controla estoque na mão.",
    "direction": "Talking head com edição moderna e promessa direta.",
    "deliverable": "Reel direct-response de produto.",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DHtF3CvxAlF/",
    "thumb": "assets/thumbs/ig_DHtF3CvxAlF.jpg",
    "poster": "assets/posters/DHtF3CvxAlF.jpg",
    "preview": "assets/previews/DHtF3CvxAlF.mp4",
    "cardImage": "assets/thumbs/ig_DHtF3CvxAlF.jpg"
  },
  {
    "id": "DYBL_r1jP3A",
    "title": "De novo na Magnos",
    "client": "Magnos Steel",
    "category": "anuncios",
    "categoryLabel": "Anúncios",
    "format": "Anúncio",
    "role": "Varejo · ritmo · CTA",
    "problem": "Manter a oferta da loja sempre fresca e desejável.",
    "direction": "Ritmo acelerado, demonstração de produto e carisma em cena.",
    "deliverable": "Anúncio de varejo para a joalheria.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/p/DYBL_r1jP3A/",
    "thumb": "assets/thumbs/ig_DYBL_r1jP3A.jpg",
    "poster": "assets/posters/DYBL_r1jP3A.jpg",
    "preview": "assets/previews/DYBL_r1jP3A.mp4",
    "cardImage": "assets/thumbs/ig_DYBL_r1jP3A.jpg"
  },
  {
    "id": "DZUo3jokhkP",
    "permalink": "https://www.instagram.com/reel/DZUo3jokhkP/",
    "title": "Corte — roubar nas séries",
    "client": "Kayky Pitondo",
    "category": "long-form",
    "categoryLabel": "Long-form",
    "format": "Corte",
    "role": "Corte · edição · legenda",
    "problem": "Reaproveitar o treino longo em conteúdo curto de alta retenção.",
    "direction": "Hook na dica e legenda destacada para segurar o reel.",
    "deliverable": "Corte vertical do long-form para o Instagram.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "thumb": "assets/thumbs/DZUo3jokhkP.jpg",
    "poster": "assets/posters/DZUo3jokhkP.jpg",
    "preview": "assets/previews/DZUo3jokhkP.mp4",
    "cardImage": "assets/thumbs/DZUo3jokhkP.jpg"
  },
  {
    "id": "DZGeYPdBiet",
    "permalink": "https://www.instagram.com/reel/DZGeYPdBiet/",
    "title": "Corte — bastidores de treino",
    "client": "Kayky Pitondo",
    "category": "long-form",
    "categoryLabel": "Long-form",
    "format": "Corte",
    "role": "Corte · b-roll · ritmo",
    "problem": "Mostrar a prática real do treino sem o vídeo ficar parado.",
    "direction": "B-roll de academia cortado no ritmo, ambientando a dica.",
    "deliverable": "Corte vertical do long-form para o Instagram.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "thumb": "assets/thumbs/DZGeYPdBiet.jpg",
    "poster": "assets/posters/DZGeYPdBiet.jpg",
    "preview": "assets/previews/DZGeYPdBiet.mp4",
    "cardImage": "assets/thumbs/DZGeYPdBiet.jpg"
  }
];
