// Fonte pública do portfólio. Só entram trabalhos, papéis e relações verificáveis.
window.PROFILE = {
  "name": "Enzo Marinho",
  "initials": "EM",
  "role": "Marketing de conteúdo em vídeo",
  "location": "Araçatuba · SP",
  "tagline_a": "Vídeo curto construído a partir do que o negócio precisa vender.",
  "tagline_b": "Estratégia e execução no mesmo lugar, com proposta construída a partir do negócio real.",
  "hero_title": "Enzo Marinho",
  "hero_sub": "Pesquisa, roteiro, captação, edição e medição no mesmo lugar.",
  "about": "Meu trabalho começa entendendo o que precisa mudar para o cliente: quem compra, o que trava a decisão e o que dá para provar em vídeo. A partir daí escolho o formato, escrevo, gravo, publico e leio o que aconteceu. Uso IA para acelerar o trabalho pesado sem terceirizar o critério.",
  "process": [
    "Diagnóstico",
    "Pauta",
    "Roteiro",
    "Captação",
    "Edição",
    "Distribuição",
    "Medição"
  ],
  "methods": [
    {
      "title": "Problema antes da ferramenta",
      "text": "Entendo público, oferta, rotina e resultado esperado antes de decidir se a solução pede conteúdo, uma página ou automação."
    },
    {
      "title": "Escopo antes do sinal",
      "text": "Entregáveis, materiais, prazo, aprovação e limites são definidos antes do pagamento para o projeto avançar sem surpresa."
    },
    {
      "title": "IA no trabalho pesado",
      "text": "Pesquisa, transcrição, copy inicial, organização, variações e tarefas repetitivas ganham velocidade com Claude, Codex e fluxos próprios."
    },
    {
      "title": "Decisão e revisão humanas",
      "text": "Eu reviso mensagem, narrativa, design, código, ritmo e contexto antes de qualquer entrega chegar ao cliente ou ao público."
    }
  ],
  "experience": {
    "employment": {
      "label": "Trabalho atual · CLT",
      "name": "VOTI Software",
      "text": "Na VOTI, trabalho de dentro da operação: penso pautas, roteiros, gravo em campo e edito conteúdos de produto, campanha e bastidores."
    },
    "independent": [
      "Negócio Sem Filtro",
      "Kayky Pitondo",
      "Magnos Steel",
      "8848 Jiu-Jitsu",
      "Lumiar Parfum · projeto encerrado"
    ]
  },
  "clients": [
    "8848 Jiu-Jitsu",
    "Kayky Pitondo",
    "Negócio Sem Filtro",
    "Magnos Steel"
  ],
  "capabilities": [
    {
      "id": "conteudo",
      "label": "Conteúdo e vídeo",
      "title": "Uma ideia vira uma frente de conteúdo.",
      "text": "Estratégia, roteiro, captação, edição, cortes e peças de campanha definidos a partir do material e do canal que precisam funcionar."
    },
    {
      "id": "presenca",
      "label": "Sites e páginas",
      "title": "A oferta ganha uma presença clara.",
      "text": "Arquitetura, copy, design e código responsivo para explicar valor e conduzir a conversa até o próximo passo."
    },
    {
      "id": "sistemas",
      "label": "Sistemas e IA",
      "title": "O gargalo repetitivo vira um fluxo confiável.",
      "text": "Automação aplicada a uma tarefa definida, com testes, documentação, limites e decisão humana onde ela importa."
    }
  ],
  "services": [
    {
      "category": "conteudo",
      "categoryLabel": "Conteúdo e vídeo",
      "title": "Frente de Conteúdo Sob Medida",
      "description": "Estratégia, roteiro, captação e edição combinados depois da leitura do material, do canal e da cadência necessária.",
      "detail": "Escopo construído após análise",
      "timeline": "Prazo definido pelo escopo",
      "revisions": "Aprovação definida na proposta",
      "includes": [
        "Objetivo e público",
        "Formatos e volume",
        "Material de origem",
        "Cadência e aprovação"
      ]
    },
    {
      "category": "presenca",
      "categoryLabel": "Sites e páginas",
      "title": "Presença Digital Sob Medida",
      "description": "Arquitetura, copy, design e código dimensionados a partir da oferta, das integrações e do próximo passo esperado.",
      "detail": "Escopo construído após análise",
      "timeline": "Prazo definido pelo escopo",
      "revisions": "Aprovação definida na proposta",
      "includes": [
        "Mensagem e arquitetura",
        "Design responsivo",
        "Desenvolvimento",
        "Publicação combinada"
      ]
    },
    {
      "category": "sistemas",
      "categoryLabel": "Sistemas e IA",
      "title": "Sistema Útil Sob Medida",
      "description": "Uma tarefa repetitiva vira um fluxo testável quando o ganho, os limites e as responsabilidades estão claros.",
      "detail": "Escopo construído após análise",
      "timeline": "Prazo definido pelo escopo",
      "revisions": "Aprovação definida na proposta",
      "includes": [
        "Mapeamento do gargalo",
        "Fluxo e integrações",
        "Testes com exemplos reais",
        "Documentação e limites"
      ]
    }
  ],
  "diagnostic": {
    "factors": [
      {
        "title": "Resultado",
        "text": "O que precisa mudar no negócio e como vamos reconhecer avanço."
      },
      {
        "title": "Porte",
        "text": "Tamanho da operação, responsabilidade e impacto de uma decisão errada."
      },
      {
        "title": "Volume",
        "text": "Quantidade real de entregas, formatos, canais e material de origem."
      },
      {
        "title": "Velocidade",
        "text": "Prazo, data fixa e custo de reorganizar a agenda para atender a urgência."
      },
      {
        "title": "Complexidade",
        "text": "Aprovações, integrações, deslocamento, risco técnico e coordenação envolvida."
      }
    ],
    "promise": "Depois da leitura, o plano mostra objetivo, entregáveis, limites, prazo, responsabilidades e investimento. Sem tabela genérica e sem inflar um projeto pequeno."
  },
  "aiRoles": [
    {
      "owner": "Enzo",
      "role": "Decisão humana",
      "text": "Diagnóstico do negócio, direção criativa, contato, captação e aprovação final."
    },
    {
      "owner": "GPT-5.6 Codex",
      "role": "Engenharia principal",
      "text": "Arquitetura, implementação, testes, acessibilidade, performance e verificação técnica."
    },
    {
      "owner": "Opus 5",
      "role": "Segunda leitura",
      "text": "Crítica estratégica e editorial, revisão de narrativa e contraponto visual."
    },
    {
      "owner": "Em comum",
      "role": "Pesquisa e revisão",
      "text": "Comparação de fontes, exploração de alternativas e revisão cruzada. Nenhum modelo publica ou decide pelo cliente."
    }
  ],
  "automation": {
    "stages": [
      {
        "title": "Começo pelo material completo",
        "text": "Recebo o episódio, a entrevista, a aula ou a gravação principal e entendo o contexto antes de separar qualquer trecho."
      },
      {
        "title": "A IA ajuda a enxergar o todo",
        "text": "Uso transcrição e análise para mapear assuntos, frases fortes e pontos que merecem uma segunda leitura."
      },
      {
        "title": "Eu escolho e organizo",
        "text": "Reviso os candidatos, separo os melhores cortes e monto uma ordem de prioridade para a entrega."
      },
      {
        "title": "Cada corte ganha acabamento",
        "text": "Ajusto abertura, ritmo, legenda e identidade seguindo exatamente o padrão aprovado pelo cliente."
      },
      {
        "title": "A entrega chega organizada",
        "text": "Vídeo longo, cortes e teasers ficam separados e prontos para entrar na rotina de publicação."
      }
    ],
    "proof": {
      "client": "Negócio Sem Filtro",
      "title": "Todos os cortes do perfil passaram pela minha edição.",
      "text": "No Negócio Sem Filtro, edito os cortes publicados do perfil, faço a seleção e o ranking dos trechos e produzo os teasers. Também participei da captação de um dos vídeos longos, sem ser responsável pela edição desse episódio completo.",
      "poster": "assets/thumbs/ig_DaBe_RIhl06.webp",
      "permalink": "https://www.instagram.com/reel/DaBe_RIhl06/",
      "profile": "https://www.instagram.com/onegociosemfiltro/",
      "signals": [
        "Todos os cortes do perfil",
        "Teasers produzidos",
        "Seleção e ranking"
      ],
      "links": [
        {
          "title": "Marketing é gasto ou retorno?",
          "url": "https://www.instagram.com/reel/DaBe_RIhl06/"
        },
        {
          "title": "IA é meio, não estrategista",
          "url": "https://www.instagram.com/onegociosemfiltro/reel/DaQEv0Blj2s/"
        },
        {
          "title": "Conteúdo que converte",
          "url": "https://www.instagram.com/onegociosemfiltro/reel/DaNgCEIFkJB/"
        },
        {
          "title": "Stories que vendem",
          "url": "https://www.instagram.com/onegociosemfiltro/reel/DaFxmK1DjRc/"
        },
        {
          "title": "IA não substitui vendedor",
          "url": "https://www.instagram.com/onegociosemfiltro/reel/DaDJWnjjn-X/"
        },
        {
          "title": "Bastidores com Clayton Khan",
          "url": "https://www.instagram.com/onegociosemfiltro/reel/DYDiclAOSod/"
        },
        {
          "title": "Faculdade vale a pena?",
          "url": "https://www.instagram.com/onegociosemfiltro/reel/DX_2dJiO8WZ/"
        }
      ]
    }
  },
  "contact": {
    "whatsapp": "https://wa.me/5518981196746?text=Oi%20Enzo%2C%20vi%20seu%20portf%C3%B3lio%20e%20quero%20entender%20meu%20pr%C3%B3ximo%20passo.%0A%0AO%20que%20precisa%20mudar%3A%20%0APrazo%3A%20%0AMaterial%20ou%20refer%C3%AAncias%3A%20",
    "instagram": "https://instagram.com/enzosmarinho",
    "linkedin": "https://www.linkedin.com/in/enzo-marinho-727200320",
    "email": "enzo.marinho@hotmail.com"
  }
};
window.CASES = [
  {
    "id": "DaBe_RIhl06",
    "permalink": "https://www.instagram.com/reel/DaBe_RIhl06/",
    "title": "Negócio Sem Filtro",
    "client": "Negócio Sem Filtro",
    "category": "edicao",
    "categoryLabel": "Edição e curadoria",
    "format": "Cortes + teasers",
    "role": "Cortes · teasers · curadoria",
    "problem": "Cada episódio precisava se transformar em uma sequência de cortes fortes, coerentes e prontos para publicação.",
    "direction": "Seleciono e ranqueio os trechos, edito cada peça vertical e produzo os teasers. Também captei um dos episódios longos.",
    "deliverable": "Todos os cortes e teasers publicados no perfil, além da captação de um dos vídeos longos.",
    "result": "Uma frente contínua de conteúdo construída a partir dos episódios do projeto.",
    "year": "2026",
    "layout": "wide",
    "orientation": "portrait",
    "featured": true,
    "thumb": "assets/thumbs/ig_DaBe_RIhl06.avif",
    "preview": "assets/hero/negocio-sem-filtro-hd.mp4",
    "cardImage": "assets/hero/negocio-sem-filtro-hd.webp",
    "heroWidth": 720,
    "heroHeight": 1280
  },
  {
    "id": "DQfTWkhiK4k",
    "title": "Funcionário perfeito",
    "client": "VOTI Software",
    "category": "direcao",
    "categoryLabel": "Direção",
    "format": "Reel",
    "role": "Roteiro · direção · edição",
    "problem": "Apresentar o software sem cair em uma explicação técnica ou em uma propaganda genérica.",
    "direction": "Transformei a ferramenta no personagem do 'funcionário perfeito' e conduzi a peça em um tom leve.",
    "deliverable": "Roteiro, direção e edição do reel para o perfil da VOTI.",
    "year": "2025",
    "layout": "wide",
    "orientation": "portrait",
    "featured": false,
    "permalink": "https://www.instagram.com/reel/DQfTWkhiK4k/",
    "thumb": "assets/thumbs/ig_DQfTWkhiK4k.jpg",
    "preview": "assets/previews/DQfTWkhiK4k.mp4",
    "cardImage": "assets/posters/DQfTWkhiK4k.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DUf-ODMDWqA",
    "title": "No tatame",
    "client": "8848 Jiu-Jitsu",
    "category": "direcao",
    "categoryLabel": "Direção",
    "format": "Reel",
    "role": "Captação · edição · ritmo",
    "problem": "Fazer quem está do lado de fora sentir a intensidade de um treino real.",
    "direction": "Gravei dentro do tatame e montei o vídeo acompanhando o ritmo dos movimentos.",
    "deliverable": "Captação e edição de um reel vertical para a academia.",
    "result": "246 likes · 38 comentários — maior alcance orgânico",
    "year": "2026",
    "layout": "tall",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DUf-ODMDWqA/",
    "thumb": "assets/thumbs/ig_DUf-ODMDWqA.jpg",
    "preview": "assets/previews/DUf-ODMDWqA.mp4",
    "cardImage": "assets/thumbs/ig_DUf-ODMDWqA.jpg",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "qBTk1irwDc4",
    "title": "Visita técnica da VOTI",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Short",
    "role": "Captação em campo · edição · motion 3D",
    "problem": "Registrar uma visita técnica da VOTI sem transformar o conteúdo em um tour parado.",
    "direction": "Gravei no espaço da Catvi durante uma visita da VOTI e usei motion para dar ritmo à apresentação. A Catvi foi o local da gravação, não minha contratante.",
    "deliverable": "Short produzido para os canais da VOTI durante a visita.",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://youtu.be/qBTk1irwDc4",
    "thumb": "assets/thumbs/qBTk1irwDc4.jpg",
    "preview": "assets/hero/qBTk1irwDc4-hd.mp4",
    "cardImage": "assets/hero/qBTk1irwDc4-hd.webp",
    "heroWidth": 720,
    "heroHeight": 1280
  },
  {
    "id": "ADKpionmFiw",
    "title": "Treino de superiores",
    "client": "Kayky Pitondo",
    "category": "long-form",
    "categoryLabel": "Long-form",
    "format": "40 min",
    "role": "Produção completa · captação · edição",
    "problem": "Produzir quase quarenta minutos de treino com clareza, ritmo e material suficiente para continuar a comunicação em cortes.",
    "direction": "Assumi a produção completa: planejei e fiz a captação, estruturei o vídeo longo, editei, finalizei a cor e derivei os cortes verticais.",
    "deliverable": "Vídeo longo e cortes verticais produzidos de ponta a ponta.",
    "year": "2026",
    "layout": "wide",
    "orientation": "landscape",
    "permalink": "https://youtu.be/ADKpionmFiw",
    "thumb": "assets/thumbs/ADKpionmFiw.jpg",
    "preview": "assets/hero/ADKpionmFiw-hd.mp4",
    "cardImage": "assets/hero/ADKpionmFiw-hd.webp",
    "heroWidth": 1280,
    "heroHeight": 720
  },
  {
    "id": "DXiIx4_kQ-0",
    "title": "Seu DRE mentiu",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Hook · demonstração · edição",
    "problem": "Explicar uma dor financeira real sem exigir que o público conheça termos de gestão.",
    "direction": "Abri com uma frase direta e mostrei o problema na tela enquanto a explicação avançava.",
    "deliverable": "Reel educativo produzido para a comunicação da VOTI.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DXiIx4_kQ-0/",
    "thumb": "assets/thumbs/ig_DXiIx4_kQ-0.jpg",
    "preview": "assets/previews/DXiIx4_kQ-0.mp4",
    "cardImage": "assets/thumbs/ig_DXiIx4_kQ-0.jpg",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DYC7byPyEnW",
    "title": "Oferta Magnos",
    "client": "Magnos Steel",
    "category": "anuncios",
    "categoryLabel": "Anúncios",
    "format": "Anúncio",
    "role": "Apresentação · cortes · CTA",
    "problem": "Apresentar a oferta rapidamente e deixar claro o próximo passo para quem assistisse.",
    "direction": "Mantive a apresentação objetiva, acelerei os cortes e fechei com uma chamada simples.",
    "deliverable": "Anúncio vertical editado e entregue para veiculação.",
    "year": "2026",
    "layout": "wide",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DYC7byPyEnW/",
    "thumb": "assets/thumbs/ig_DYC7byPyEnW.jpg",
    "preview": "assets/previews/DYC7byPyEnW.mp4",
    "cardImage": "assets/thumbs/ig_DYC7byPyEnW.jpg",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DUQ8YNYEc4z",
    "title": "Novo sucesso na região",
    "client": "Lumiar Parfum",
    "category": "anuncios",
    "categoryLabel": "Anúncios",
    "format": "Anúncio",
    "role": "Voz off · design · edição",
    "problem": "Posicionar o perfume como novidade desejada na região.",
    "direction": "Voz off conduzindo a narrativa com design e edição alinhados à marca.",
    "deliverable": "Anúncio com voz off e identidade visual aplicada.",
    "year": "2026",
    "status": "Projeto encerrado",
    "layout": "tall",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DUQ8YNYEc4z/",
    "thumb": "assets/thumbs/ig_DUQ8YNYEc4z.webp",
    "preview": "assets/previews/DUQ8YNYEc4z.mp4",
    "cardImage": "assets/thumbs/ig_DUQ8YNYEc4z.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DSldztZCA9P",
    "title": "Carta ao Papai Noel",
    "client": "VOTI Software",
    "category": "direcao",
    "categoryLabel": "Direção",
    "format": "Reel",
    "role": "Narrativa · atuação · branding",
    "problem": "Entrar no clima de fim de ano sem fazer uma peça que poderia ser de qualquer marca.",
    "direction": "Construí uma narrativa curta, conduzi a atuação e amarrei o fechamento ao universo da VOTI.",
    "deliverable": "Roteiro, direção e edição do reel de fim de ano.",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DSldztZCA9P/",
    "thumb": "assets/thumbs/ig_DSldztZCA9P.jpg",
    "preview": "assets/previews/DSldztZCA9P.mp4",
    "cardImage": "assets/thumbs/ig_DSldztZCA9P.jpg",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DWpa8TQCKvX",
    "title": "Qual produto dá mais lucro?",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Copy · produto · retenção",
    "problem": "Responder uma pergunta importante de gestão em um formato curto e fácil de acompanhar.",
    "direction": "Organizei o argumento em uma sequência direta e usei a edição para sustentar a explicação.",
    "deliverable": "Reel de produto produzido para o perfil da VOTI.",
    "year": "2026",
    "layout": "wide",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DWpa8TQCKvX/",
    "thumb": "assets/thumbs/ig_DWpa8TQCKvX.webp",
    "preview": "assets/previews/DWpa8TQCKvX.mp4",
    "cardImage": "assets/thumbs/ig_DWpa8TQCKvX.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DKkdTYyItAy",
    "title": "Bastidores de uma visita da VOTI",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Captação em campo · vlog · edição",
    "problem": "Mostrar a equipe da VOTI em campo sem encenar uma demonstração.",
    "direction": "Registrei uma visita da VOTI no espaço da Catvi e montei os bastidores em linguagem de vlog. A Catvi foi o local da gravação, não minha contratante.",
    "deliverable": "Reel publicado pela VOTI sobre a visita.",
    "result": "104 likes — 1º pico orgânico da VOTI",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DKkdTYyItAy/",
    "thumb": "assets/thumbs/ig_DKkdTYyItAy.webp",
    "preview": "assets/previews/DKkdTYyItAy.mp4",
    "cardImage": "assets/thumbs/ig_DKkdTYyItAy.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DaQEv0Blj2s",
    "title": "IA é meio, não estrategista",
    "client": "Negócio Sem Filtro",
    "category": "edicao",
    "categoryLabel": "Corte de podcast",
    "format": "Reel",
    "role": "Seleção · edição · legendas",
    "problem": "Transformar uma resposta do episódio em uma ideia completa e assistível fora da conversa longa.",
    "direction": "Escolhi o trecho, organizei a abertura e finalizei ritmo e legendas dentro do padrão do perfil.",
    "deliverable": "Corte vertical publicado no perfil Negócio Sem Filtro.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/onegociosemfiltro/reel/DaQEv0Blj2s/",
    "thumb": "assets/posters/nsf_DaQEv0Blj2s.jpg",
    "cardImage": "assets/posters/nsf_DaQEv0Blj2s.jpg",
    "heroWidth": 1080,
    "heroHeight": 1920
  },
  {
    "id": "DYDiclAOSod",
    "title": "Bastidores com Clayton Khan",
    "client": "Negócio Sem Filtro",
    "category": "edicao",
    "categoryLabel": "Corte de podcast",
    "format": "Reel",
    "role": "Seleção · edição · legendas",
    "problem": "Encontrar um momento de bastidor que funcionasse como conteúdo por conta própria.",
    "direction": "Priorizei o trecho, mantive a conversa natural e dei acabamento vertical com ritmo e legendas.",
    "deliverable": "Corte vertical publicado no perfil Negócio Sem Filtro.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/onegociosemfiltro/reel/DYDiclAOSod/",
    "thumb": "assets/posters/nsf_DYDiclAOSod.jpg",
    "cardImage": "assets/posters/nsf_DYDiclAOSod.jpg",
    "heroWidth": 640,
    "heroHeight": 1136
  },
  {
    "id": "DX_2dJiO8WZ",
    "title": "Faculdade vale a pena?",
    "client": "Negócio Sem Filtro",
    "category": "edicao",
    "categoryLabel": "Corte de podcast",
    "format": "Reel",
    "role": "Seleção · edição · legendas",
    "problem": "Dar contexto suficiente para uma pergunta ampla funcionar em menos de um minuto.",
    "direction": "Estruturei a entrada pelo conflito da pergunta e finalizei o corte para consumo vertical.",
    "deliverable": "Corte vertical publicado no perfil Negócio Sem Filtro.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/onegociosemfiltro/reel/DX_2dJiO8WZ/",
    "thumb": "assets/posters/nsf_DX_2dJiO8WZ.jpg",
    "cardImage": "assets/posters/nsf_DX_2dJiO8WZ.jpg",
    "heroWidth": 640,
    "heroHeight": 1136
  }
];
window.EXTRA_CLIPS = [
  {
    "id": "DaNgCEIFkJB",
    "title": "Conteúdo que converte",
    "client": "Negócio Sem Filtro",
    "category": "edicao",
    "categoryLabel": "Corte de podcast",
    "format": "Reel",
    "role": "Seleção · edição · legendas",
    "direction": "Corte selecionado e finalizado para transformar uma ideia do episódio em conteúdo autônomo.",
    "deliverable": "Corte vertical publicado no perfil Negócio Sem Filtro.",
    "year": "2026",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/onegociosemfiltro/reel/DaNgCEIFkJB/",
    "thumb": "assets/posters/nsf_DaNgCEIFkJB.jpg",
    "cardImage": "assets/posters/nsf_DaNgCEIFkJB.jpg",
    "heroWidth": 1080,
    "heroHeight": 1920
  },
  {
    "id": "DaFxmK1DjRc",
    "title": "Stories que vendem",
    "client": "Negócio Sem Filtro",
    "category": "edicao",
    "categoryLabel": "Corte de podcast",
    "format": "Reel",
    "role": "Seleção · edição · legendas",
    "direction": "Corte selecionado pela força prática da ideia e finalizado no padrão visual do perfil.",
    "deliverable": "Corte vertical publicado no perfil Negócio Sem Filtro.",
    "year": "2026",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/onegociosemfiltro/reel/DaFxmK1DjRc/",
    "thumb": "assets/posters/nsf_DaFxmK1DjRc.jpg",
    "cardImage": "assets/posters/nsf_DaFxmK1DjRc.jpg",
    "heroWidth": 1080,
    "heroHeight": 1920
  },
  {
    "id": "DaDJWnjjn-X",
    "title": "IA não substitui vendedor",
    "client": "Negócio Sem Filtro",
    "category": "edicao",
    "categoryLabel": "Corte de podcast",
    "format": "Reel",
    "role": "Seleção · edição · legendas",
    "direction": "Corte construído ao redor de uma pergunta forte, com ritmo e legendas para consumo vertical.",
    "deliverable": "Corte vertical publicado no perfil Negócio Sem Filtro.",
    "year": "2026",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/onegociosemfiltro/reel/DaDJWnjjn-X/",
    "thumb": "assets/posters/nsf_DaDJWnjjn-X.jpg",
    "cardImage": "assets/posters/nsf_DaDJWnjjn-X.jpg",
    "heroWidth": 1080,
    "heroHeight": 1920
  },
  {
    "id": "DUJfuJsCPir",
    "title": "WhatsApp conectado",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Demonstração · produto · clareza",
    "problem": "Mostrar uma integração técnica sem transformar o vídeo em tutorial frio.",
    "direction": "Roteiro guiado por ação na tela, com ritmo de demonstração curta.",
    "deliverable": "Reel de produto para explicar uma função específica.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DUJfuJsCPir/",
    "thumb": "assets/thumbs/ig_DUJfuJsCPir.webp",
    "preview": "assets/previews/DUJfuJsCPir.mp4",
    "cardImage": "assets/thumbs/ig_DUJfuJsCPir.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DV9deuiCHea",
    "title": "Loja física + online",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Copy · dor real · produto",
    "problem": "Transformar retrabalho de estoque e preço em uma dor fácil de reconhecer.",
    "direction": "Começo por pergunta direta e conexão com situação real de varejo.",
    "deliverable": "Reel educativo para topo de funil.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DV9deuiCHea/",
    "thumb": "assets/thumbs/ig_DV9deuiCHea.webp",
    "preview": "assets/previews/DV9deuiCHea.mp4",
    "cardImage": "assets/thumbs/ig_DV9deuiCHea.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DW4c4OjkdA5",
    "title": "Renda extra Lumiar",
    "client": "Lumiar Parfum",
    "category": "anuncios",
    "categoryLabel": "Anúncios",
    "format": "Anúncio",
    "role": "Oferta · captação · CTA",
    "problem": "Apresentar uma oportunidade comercial sem parecer panfleto estático.",
    "direction": "Roteiro de oferta com presença em cena e CTA simples.",
    "deliverable": "Anúncio vertical para campanha de revenda.",
    "year": "2026",
    "status": "Projeto encerrado",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/lumiar.parfum/reel/DW4c4OjkdA5/",
    "thumb": "assets/thumbs/ig_DW4c4OjkdA5.jpg",
    "preview": "assets/previews/DW4c4OjkdA5.mp4",
    "cardImage": "assets/thumbs/ig_DW4c4OjkdA5.jpg",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DTgXN2FiDV6",
    "title": "Sintoma de gestão",
    "client": "VOTI Software",
    "category": "direcao",
    "categoryLabel": "Direção",
    "format": "Reel",
    "role": "Hook · analogia · edição",
    "problem": "Chamar atenção para uma dor de gestão usando uma entrada mais memorável.",
    "direction": "Abordagem por sintoma e cura para tornar o tema técnico mais assistível.",
    "deliverable": "Reel de awareness para social.",
    "result": "905 views · 122 likes no Instagram",
    "year": "2026",
    "layout": "standard",
    "orientation": "landscape",
    "permalink": "https://www.instagram.com/reel/DTgXN2FiDV6/",
    "thumb": "assets/thumbs/ig_DTgXN2FiDV6.webp",
    "cardImage": "assets/posters/DTgXN2FiDV6.webp",
    "preview": "assets/previews/DTgXN2FiDV6.mp4",
    "heroWidth": 480,
    "heroHeight": 270
  },
  {
    "id": "blYFchVi4xg",
    "title": "Sistema de Natal",
    "client": "VOTI Software",
    "category": "anuncios",
    "categoryLabel": "Anúncios",
    "format": "Short",
    "role": "Sazonal · roteiro · edição",
    "problem": "Aproveitar uma data comercial sem perder o vínculo com produto.",
    "direction": "Gancho sazonal com linguagem leve e foco em preparação de venda.",
    "deliverable": "Short sazonal para campanha de fim de ano.",
    "result": "≈1,7 mil views no YouTube",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://youtu.be/blYFchVi4xg",
    "thumb": "assets/thumbs/blYFchVi4xg.jpg",
    "preview": "assets/previews/blYFchVi4xg.mp4",
    "cardImage": "assets/posters/blYFchVi4xg.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DGLMxcXRRJ4",
    "title": "Caso na Padaria Bom Menino",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Vlog · caso real · prova",
    "problem": "Gerar confiança no sistema com um cliente real, não com promessa.",
    "direction": "Estudo de caso gravado no ponto do cliente, com autoridade e números.",
    "deliverable": "Reel de prova social em campo.",
    "year": "2025",
    "layout": "standard",
    "orientation": "landscape",
    "permalink": "https://www.instagram.com/reel/DGLMxcXRRJ4/",
    "thumb": "assets/thumbs/ig_DGLMxcXRRJ4.jpg",
    "preview": "assets/previews/DGLMxcXRRJ4.mp4",
    "cardImage": "assets/posters/DGLMxcXRRJ4.jpg",
    "heroWidth": 480,
    "heroHeight": 270
  },
  {
    "id": "DOzGHz2iLGz",
    "title": "E se você fosse de uma oficina?",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Verticalização · energia · edição",
    "problem": "Mostrar que o sistema atende a um nicho específico, não só o genérico.",
    "direction": "Infotenimento B2B de alta energia focado no segmento.",
    "deliverable": "Reel de verticalização para oficinas.",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DOzGHz2iLGz/",
    "thumb": "assets/thumbs/ig_DOzGHz2iLGz.webp",
    "preview": "assets/previews/DOzGHz2iLGz.mp4",
    "cardImage": "assets/thumbs/ig_DOzGHz2iLGz.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DHtF3CvxAlF",
    "title": "Estoque no automático",
    "client": "VOTI Software",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Talking head · direct response",
    "problem": "Vender produtividade para quem ainda controla estoque na mão.",
    "direction": "Talking head com edição moderna e promessa direta.",
    "deliverable": "Reel direct-response de produto.",
    "year": "2025",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DHtF3CvxAlF/",
    "thumb": "assets/thumbs/ig_DHtF3CvxAlF.webp",
    "preview": "assets/previews/DHtF3CvxAlF.mp4",
    "cardImage": "assets/thumbs/ig_DHtF3CvxAlF.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DV8UfkSDSa3",
    "title": "Perfume de R$ 600?",
    "client": "Lumiar Parfum",
    "category": "anuncios",
    "categoryLabel": "Anúncios",
    "format": "Anúncio",
    "role": "Comparativo · carisma · edição",
    "problem": "Vender um perfume acessível sem matar o desejo pelo de luxo.",
    "direction": "Comparação de custo-benefício com a energia do creator conduzindo.",
    "deliverable": "Anúncio de comparação para revenda.",
    "year": "2026",
    "status": "Projeto encerrado",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DV8UfkSDSa3/",
    "thumb": "assets/thumbs/ig_DV8UfkSDSa3.webp",
    "preview": "assets/previews/DV8UfkSDSa3.mp4",
    "cardImage": "assets/thumbs/ig_DV8UfkSDSa3.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DWozrqUjnsi",
    "title": "Vender sem gastar nada",
    "client": "Lumiar Parfum",
    "category": "anuncios",
    "categoryLabel": "Anúncios",
    "format": "Anúncio",
    "role": "Pitch · oportunidade · clareza",
    "problem": "Apresentar uma revenda de baixo risco de forma crível.",
    "direction": "Pitch direto detalhando a oportunidade passo a passo.",
    "deliverable": "Anúncio de revenda para captação.",
    "year": "2026",
    "status": "Projeto encerrado",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DWozrqUjnsi/",
    "thumb": "assets/thumbs/ig_DWozrqUjnsi.webp",
    "preview": "assets/previews/DWozrqUjnsi.mp4",
    "cardImage": "assets/thumbs/ig_DWozrqUjnsi.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DT_OjkyEYwP",
    "title": "Cheirando a camisa da ex",
    "client": "Lumiar Parfum",
    "category": "conteudo",
    "categoryLabel": "Conteúdo",
    "format": "Reel",
    "role": "Esquete · humor · edição",
    "problem": "Destacar um perfume sem o vídeo parecer um anúncio.",
    "direction": "Esquete cômico que entrega o benefício pela piada.",
    "deliverable": "Reel cômico para awareness da marca.",
    "year": "2026",
    "status": "Projeto encerrado",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/reel/DT_OjkyEYwP/",
    "thumb": "assets/thumbs/ig_DT_OjkyEYwP.webp",
    "preview": "assets/previews/DT_OjkyEYwP.mp4",
    "cardImage": "assets/thumbs/ig_DT_OjkyEYwP.webp",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DYBL_r1jP3A",
    "title": "De novo na Magnos",
    "client": "Magnos Steel",
    "category": "anuncios",
    "categoryLabel": "Anúncios",
    "format": "Anúncio",
    "role": "Varejo · ritmo · CTA",
    "problem": "Manter a oferta da loja sempre fresca e desejável.",
    "direction": "Ritmo acelerado, demonstração de produto e carisma em cena.",
    "deliverable": "Anúncio de varejo para a joalheria.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "permalink": "https://www.instagram.com/p/DYBL_r1jP3A/",
    "thumb": "assets/thumbs/ig_DYBL_r1jP3A.jpg",
    "preview": "assets/previews/DYBL_r1jP3A.mp4",
    "cardImage": "assets/thumbs/ig_DYBL_r1jP3A.jpg",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DZUo3jokhkP",
    "permalink": "https://www.instagram.com/reel/DZUo3jokhkP/",
    "title": "Corte — roubar nas séries",
    "client": "Kayky Pitondo",
    "category": "long-form",
    "categoryLabel": "Long-form",
    "format": "Corte",
    "role": "Corte · edição · legenda",
    "problem": "Reaproveitar o treino longo em conteúdo curto de alta retenção.",
    "direction": "Hook na dica e legenda destacada para segurar o reel.",
    "deliverable": "Corte vertical do long-form para o Instagram.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "thumb": "assets/thumbs/DZUo3jokhkP.jpg",
    "preview": "assets/previews/DZUo3jokhkP.mp4",
    "cardImage": "assets/thumbs/DZUo3jokhkP.jpg",
    "heroWidth": 480,
    "heroHeight": 854
  },
  {
    "id": "DZGeYPdBiet",
    "permalink": "https://www.instagram.com/reel/DZGeYPdBiet/",
    "title": "Corte — bastidores de treino",
    "client": "Kayky Pitondo",
    "category": "long-form",
    "categoryLabel": "Long-form",
    "format": "Corte",
    "role": "Corte · b-roll · ritmo",
    "problem": "Mostrar a prática real do treino sem o vídeo ficar parado.",
    "direction": "B-roll de academia cortado no ritmo, ambientando a dica.",
    "deliverable": "Corte vertical do long-form para o Instagram.",
    "year": "2026",
    "layout": "standard",
    "orientation": "portrait",
    "thumb": "assets/thumbs/DZGeYPdBiet.jpg",
    "preview": "assets/previews/DZGeYPdBiet.mp4",
    "cardImage": "assets/thumbs/DZGeYPdBiet.jpg",
    "heroWidth": 480,
    "heroHeight": 854
  }
];
