import './official.css';
const colors=[['Uva','#221037','Base'],['Violeta','#8648FF','Reconhecimento'],['Lima','#EAFF87','Acento'],['Pérola','#F7F4FF','Respiro']];
export default function BrandGuide({portfolioHref='/'}:{portfolioHref?:string}){return <main className="official-brand">
 <header><a href={portfolioHref}>← Portfólio</a><span>Identidade visual / 01.0</span></header>
 <section className="official-intro"><span className="brand-overline">ENZO MARINHO / VÍDEO, CRIAÇÃO E APOIO</span><h1>Boas histórias.<br/>No <em>ritmo</em> certo.</h1><p>Uma marca pessoal feita para ajudar quem quer produzir e dar suporte a quem já cria.</p><span className="brand-approval">Direção aprovada em 09.09.2026</span></section>
 <section className="official-section"><div className="official-heading"><span>01 / Assinatura</span><h2>O seu nome.<br/>Com presença.</h2></div><div className="official-logos"><div><img src="./brand/enzo-marinho-perola.svg" alt="Enzo Marinho, assinatura clara"/></div><div><img src="./brand/enzo-marinho-uva.svg" alt="Enzo Marinho, assinatura escura"/></div></div><p>A assinatura é tipográfica. Enquadramento e linha de ritmo acompanham as composições; não precisam acompanhar o nome em todo uso.</p></section>
 <section className="official-section"><div className="official-heading"><span>02 / Cor</span><h2>Contraste que<br/>tem direção.</h2></div><div className="official-swatches">{colors.map(([name,hex,role])=><div key={name}><i style={{background:hex}}/><strong>{name}</strong><span>{hex}</span><small>{role}</small></div>)}</div><p>Uva e pérola sustentam a leitura. Violeta cria reconhecimento. Lima marca uma palavra, um ponto de edição ou uma chamada. O vídeo preserva as próprias cores.</p></section>
 <section className="official-section"><div className="official-heading"><span>03 / Tipografia</span><h2>Inter Tight.</h2></div><div className="official-type"><strong>Aa / ação, conexão.</strong><p>Direta no texto. Presente no título.<br/>Pesos 400, 600, 700 e 800.</p></div><p>Fonte local com licença SIL Open Font License. Arquivos e licença acompanham o kit.</p></section>
 <section className="official-section"><div className="official-heading"><span>04 / Em cena</span><h2>A mesma marca.<br/>Em outros formatos.</h2></div><div className="official-applications"><div><img src="./brand/abertura-16x9.svg" alt="Abertura horizontal: começa com uma ideia"/><img src="./brand/encerramento-16x9.svg" alt="Encerramento: a próxima ideia pode ser a sua"/></div><img src="./brand/capa-9x16.svg" alt="Capa vertical: boas histórias, no ritmo certo"/></div><p>Matrizes estáticas em SVG e PNG. A animação e a aplicação sobre uma gravação serão combinadas por projeto.</p></section>
 <footer><a href={portfolioHref}>Ver a marca com os trabalhos reais ↗</a><span>Enzo Marinho / 2026</span></footer>
 </main>}
